CREATE DATABASE universe
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
-- Table: public.planet

-- DROP TABLE public.planet;

CREATE TABLE public.planet
(
    planetid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    CONSTRAINT "Planet_pkey" PRIMARY KEY (planetid)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.planet
    OWNER to postgres;

-- Table: public.planetlog

-- DROP TABLE public.planetlog;

CREATE TABLE public.planetlog
(
    planetlogid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    planetid bigint NOT NULL,
    log text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Rebel_Log_pkey" PRIMARY KEY (planetlogid)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.planetlog
    OWNER to postgres;
-- Index: fki_planet_fg

-- DROP INDEX public.fki_planet_fg;

CREATE INDEX fki_planet_fg
    ON public.planetlog USING btree
    (planetid ASC NULLS LAST)
    TABLESPACE pg_default;