INSERT INTO public."Planet"("Name") VALUES ('AhchTo');
INSERT INTO public."Planet"("Name") VALUES ('Alderaan');
INSERT INTO public."Planet"("Name") VALUES ('Anoat');
INSERT INTO public."Planet"("Name") VALUES ('Atollon');
INSERT INTO public."Planet"("Name") VALUES ('Base Starkiller');
INSERT INTO public."Planet"("Name") VALUES ('Bespin');
INSERT INTO public."Planet"("Name") VALUES ('Cato Neimoidia');
INSERT INTO public."Planet"("Name") VALUES ('Christophsis');
INSERT INTO public."Planet"("Name") VALUES ('Concord Dawn');
INSERT INTO public."Planet"("Name") VALUES ('Corellia');
INSERT INTO public."Planet"("Name") VALUES ('Coruscant');
INSERT INTO public."Planet"("Name") VALUES ('Crait');
INSERT INTO public."Planet"("Name") VALUES ('Cantonica');
INSERT INTO public."Planet"("Name") VALUES ('DQar');
INSERT INTO public."Planet"("Name") VALUES ('Dagobah');
INSERT INTO public."Planet"("Name") VALUES ('Dantooine');
INSERT INTO public."Planet"("Name") VALUES ('Dathomir');
INSERT INTO public."Planet"("Name") VALUES ('Devaron');
INSERT INTO public."Planet"("Name") VALUES ('Eadu');
INSERT INTO public."Planet"("Name") VALUES ('Endor');
INSERT INTO public."Planet"("Name") VALUES ('Exegol');
INSERT INTO public."Planet"("Name") VALUES ('Felucia');
INSERT INTO public."Planet"("Name") VALUES ('Florrum');
INSERT INTO public."Planet"("Name") VALUES ('Geonosis');
INSERT INTO public."Planet"("Name") VALUES ('Hosnian Prime');
INSERT INTO public."Planet"("Name") VALUES ('Hoth');
INSERT INTO public."Planet"("Name") VALUES ('Iego');
INSERT INTO public."Planet"("Name") VALUES ('Ilum');
INSERT INTO public."Planet"("Name") VALUES ('Iridonia');
INSERT INTO public."Planet"("Name") VALUES ('Jakku');
INSERT INTO public."Planet"("Name") VALUES ('Jedha');
INSERT INTO public."Planet"("Name") VALUES ('Kamino');
INSERT INTO public."Planet"("Name") VALUES ('Kashyyyk');
INSERT INTO public."Planet"("Name") VALUES ('Kessel');
INSERT INTO public."Planet"("Name") VALUES ('Lahmu');
INSERT INTO public."Planet"("Name") VALUES ('Lothal');
INSERT INTO public."Planet"("Name") VALUES ('Malachor');
INSERT INTO public."Planet"("Name") VALUES ('Malastare');
INSERT INTO public."Planet"("Name") VALUES ('Mandalore');
INSERT INTO public."Planet"("Name") VALUES ('Maridun');
INSERT INTO public."Planet"("Name") VALUES ('Mon Calamari');
INSERT INTO public."Planet"("Name") VALUES ('Moraband');
INSERT INTO public."Planet"("Name") VALUES ('Mortis');
INSERT INTO public."Planet"("Name") VALUES ('Mustafar');
INSERT INTO public."Planet"("Name") VALUES ('Mygeeto');
INSERT INTO public."Planet"("Name") VALUES ('Naboo');
INSERT INTO public."Planet"("Name") VALUES ('Nal Hutta');
INSERT INTO public."Planet"("Name") VALUES ('Onderon');
INSERT INTO public."Planet"("Name") VALUES ('Ord Mantell');
INSERT INTO public."Planet"("Name") VALUES ('Polis Massa');
INSERT INTO public."Planet"("Name") VALUES ('Rishi');
INSERT INTO public."Planet"("Name") VALUES ('Rodia');
INSERT INTO public."Planet"("Name") VALUES ('Ruusan');
INSERT INTO public."Planet"("Name") VALUES ('Ryloth');
INSERT INTO public."Planet"("Name") VALUES ('Scarif');
INSERT INTO public."Planet"("Name") VALUES ('Shili');
INSERT INTO public."Planet"("Name") VALUES ('Subterrel');
INSERT INTO public."Planet"("Name") VALUES ('Sullust');
INSERT INTO public."Planet"("Name") VALUES ('Takodana');
INSERT INTO public."Planet"("Name") VALUES ('Tatooine');
INSERT INTO public."Planet"("Name") VALUES ('Toydaria');
INSERT INTO public."Planet"("Name") VALUES ('Trandosha');
INSERT INTO public."Planet"("Name") VALUES ('Umbara');
INSERT INTO public."Planet"("Name") VALUES ('Utapau');
INSERT INTO public."Planet"("Name") VALUES ('Wobani');